version: '2'
services:
  db:
    image: postgres
  web:
    image: phoenix13
    command: mix phx.server
    volumes:
      - ./projects:/projects
    working_dir: "/projects/${PHOENIX13_PROJECT}"
    ports:
      - "4000:4000"
    depends_on:
      - db
